config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders
  patch '/orders/:id/update_status', to: 'orders#update_status', as: 'update_status'
  root to: "products#index"
end

app/views/shared/_navbar.html.erb
  <header class="px-3 py-2 bg-light text-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to root_path, class: "d-flex align-items-center me-lg-auto" do %>
          <%= image_pack_tag "media/images/mostacho_logo.png", width: "80", height: "80" %>
        <% end %>

        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">          
          <% if user_signed_in? %>
            <li>
              <%= link_to new_order_path, class: "nav-link text-dark" do %>
                <i class="fas fa-plus fa-2x mx-2 bi d-block mx-auto mb-1"></i>
                Nueva Orden
              <% end %>
            </li>
            <li>
              <%= link_to orders_path, class: "nav-link text-dark" do %>
                <i class="fas fa-table fa-2x mx-2 bi d-block mx-auto mb-1"></i>
                Órdenes
              <% end %>
            </li>
          <% end %>
          
          <li>
            <%= link_to products_path, class: "nav-link text-dark" do %>
              <i class="fas fa-birthday-cake fa-2x mx-2 bi d-block mx-auto mb-1"></i>
              Productos
            <% end %>
          </li>
          </li>
          <li>
            <% if user_signed_in? %>
              <%= link_to destroy_user_session_path, class: "nav-link text-dark", method: :delete do %>
                <i class="far fa-user fa-2x mx-2 bi d-block mx-auto mb-1"></i>
                Cerrar Sesión
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "nav-link text-dark" do %>
                <i class="far fa-user fa-2x mx-2 bi d-block mx-auto mb-1"></i>
                Iniciar Sesión
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </header>

app/views/shared/_new_product_btn.html.erb
<%= turbo_frame_tag "new_product", class: "d-flex justify-content-center align-items-center" do %>
    <%= link_to 'Nuevo Producto', new_product_path, class: "btn btn-primary my-2" %>
<% end %>

app/views/shared/_toast.html.erb
<div data-controller="toast" class="toast" data-delay="5000" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <% if action_name == "create" %>
      <i class="fas fa-check pe-1"></i>
    <% elsif action_name == "update" %>
      <i class="far fa-edit pe-1"></i>
    <% elsif action_name == "destroy" %>
      <i class="far fa-trash-alt pe-1"></i>
    <% else %>
      <i class="fas fa-question"></i>
    <% end %>
    <strong class="me-auto"><%= title %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
    <%= message %>
  </div>
</div>