config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders
  patch '/orders/:id/update_status', to: 'orders#update_status', as: 'update_status'
  root to: "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :invoices
    has_many :products, through: :invoices
    validates :name, :delivery_date, :status, presence: true
    validate :date_equal_or_after_today, on: :create
    validates :status, inclusion: {in: %w(active ready_to_deliver complete)}
    accepts_nested_attributes_for :invoices

    def create_invoices(products)
        products.each do |k, v|
            if v.to_i > 0
                i = Invoice.create(order_id: self.id, product_id: k.to_i, quantity: v.to_i)
            end
        end
    end

    def edit_invoices(products)
        products.each do |k,val|
            if val.to_i > 0 
                i = Invoice.find_by(product_id: k.to_i, order_id: self.id)
                if(!i.nil? && i.quantity != val.to_i )
                    #this means that the invoice exists, but it doesn't have the same quantity
                    i.update(quantity: val.to_i)
                elsif(i.nil?)
                    Invoice.create(order_id: self.id, product_id: k.to_i, quantity: val.to_i)
                end
            end
        end
    end

    def get_price
        price = 0
        invoices = Invoice.where(order_id: self.id)
        invoices.each do |i|
            price += Product.find_by(id: i.product_id).price * i.quantity
        end

        return price
    end

    def get_status
        return "Lista para Entregar" if self.status == "ready_to_deliver"
        return "Activa" if self.status == "active"
        return "Completada" if self.status == "complete"
        
        return self.status.capitalize
    end

    def change_status
        if self.status == "active"
            self.status = "ready_to_deliver"
        elsif self.status == "ready_to_deliver"
            self.status = "complete"
        end
    end

    def self.active_orders
        Order.where(status: ["active", "ready_to_deliver"])
    end

    def self.completed_orders
        Order.where(status: "complete")
    end

    private

    def date_equal_or_after_today
        return if delivery_date.blank?
        
        if delivery_date < Date.today
            errors.add(:delivery_date, "Delivery date must be today onwards")
        end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy, :update_status]
    before_action :set_products, only: [:edit, :new, :update, :create]
    before_action :set_invoices, only: :show
    before_action :authenticate_user!

    def index
        @active_orders = Order.active_orders.order(delivery_date: :asc)
        @completed_orders = Order.completed_orders.order(delivery_date: :desc).limit(20)
    end

    def show

    end

    def edit

    end

    def new
        @order = Order.new
        Product.count.times {@order.invoices.build}
    end

    def create
        @order = Order.new(name: order_params[:name], delivery_date: order_params[:delivery_date], status: "active")

        respond_to do |format|
            if @order.save
                GenerateInvoices.call({order: @order, products: order_params[:products]})
                format.html { redirect_to @order, notice: "Product was successfully created" }
                format.json { render :show, status: :created, location: @order }
            else
                format.html { render :new }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @order.update(name: order_params[:name], delivery_date: order_params[:delivery_date], status: order_params[:status])
                EditInvoices.call({order: @order, products: order_params[:products]})
                format.html {redirect_to @order, notice: 'Order was successfully updated.'}
                format.json { render :show, status: :ok, location: @order }
            else
                format.html { render :edit }
                format.json { render json: @order.errors, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @order.destroy
        respond_to do |format|
            format.html { redirect_to orders_url, notice: 'Order was successfully deleted' }
            format.json { head :no_content }
        end
    end

    #custom method to only change the status of an order
    def update_status
        @order.change_status
        respond_to do |format|
            if @order.save
                format.html {redirect_to orders_path, notice: "Status change for #{@order.name}'s order"}
                format.json {render :index, status: :ok, location: @order}
            else
                format.html {redirect_to orders_path}
                format.json {render json: @order.errors, status: :unprocessable_entity}
            end
        end
    end

    private
    def set_order
        @order = Order.find_by(id: params[:id])
    end

    def set_products
        @products = Product.all
    end

    def set_invoices
        @invoices = Invoice.where(order_id: @order.id)
    end

    def order_params
        params.require(:order).permit(:name, :delivery_date, :status, products: {})
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<section>
<%= simple_form_for @order do |f| %>
  <!--Grid row-->
  <div class="row">
    <!--Grid column-->
    <div class="col-lg-8">
        <!-- Card -->
        <div class="card wish-list mb-3">
            <div class="card-body">
                <h5 class="mb-4">Productos</h5>
                <%= f.simple_fields_for :products do |ff| %>
                    <% @products.each do |p| %>
                        <div class="row mb-4">
                            <div class="col-md-5 col-lg-3 col-xl-3">
                                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                    <% if p.photo.attached? %>
                                      <%= image_tag p.photo, class: "img-fluid w-100"%>
                                    <% else %>
                                      <img class="img-fluid w-100" src="https://expertphotography.com/wp-content/uploads/2019/03/Chocolate-Cake-Darina-Kopcok-Expert-Phtography.jpg" alt="Sample">
                                    <% end %>
                                </div>
                            </div>
                            <div class="col-md-7 col-lg-9 col-xl-9">
                                <div>
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <h5><%= p.name %></h5>
                                        </div>
                                        <div>
                                            <div class="def-number-input number-input safari_only mb-0 w-100">
                                                <button type="button" onclick="subNum(<%= p.id %>, <%= p.price %>)" class="btn btn-outline-dark" id="subBtn[<%= p.id %>]"> - </button>
                                                <%= ff.input_field p.id.to_s, class: 'quantity w-25 text-center', label: false, readonly: true, value: Invoice.find_by(order_id: @order.id, product_id: p.id).nil? ? 0 : Invoice.find_by(order_id: @order.id, product_id: p.id).quantity %>
                                                <button type="button" onclick="addNum(<%= p.id %>, <%= p.price %>)" class="btn btn-outline-dark" id="addBtn[<%= p.id %>]"> + </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <p class="mb-0"><span><strong>$<%= p.price %></strong></span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="mb-4">
                    <% end %>
                <% end %>     
            </div>
        </div>
        <!-- Card -->

      
        <% if controller.action_name == "edit" %>
            <!-- Card -->
            <div class="card mb-3">
                <div class="card-body">

                <h5 class="mb-4">Fecha de Entrega</h5>
                <%= f.input :status, collection: ['active', 'ready_to_deliver', 'complete'], class: "mb-0", input_html: {value: @order.status, class: "form-control w-25"} %>
                
                </div>
            </div>
            <!-- Card -->
        <% end %>

      <!-- Card -->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4">

      <!-- Card -->
      <div class="card mb-3">
        <div class="card-body">

          <h5 class="mb-3">Información de Orden</h5>

          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Nombre
              <span><%= f.input :name, label: false, input_html: {class: "form-control"} %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
              Fecha de Entrega
              <span><%= f.input :delivery_date, as: :date, html5: true, label: false, input_html: {value: Date.today, class: "form-control"} %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
              <div>
                <strong>Total</strong>
              </div>
              <span id="totalCost"><strong>$<%= @order.get_price %></strong></span>
            </li>
          </ul>

          <% if controller.action_name == "new" %>
            <%= f.submit "Crear Orden", class: "btn btn-primary btn-block waves-effect waves-light" %>
          <% else %>
            <%= f.submit "Actualizar Orden", class: "btn btn-primary btn-block waves-effect waves-light" %>
          <% end %>

        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->
<% end %>
</section>
<!--Section: Block Content-->

<script>
  function updateCost(price, evaluator) {
    newPrice = 0;
    totalCost = document.querySelector("#totalCost").children[0].textContent;
    totalCost = totalCost.substring(1);
    totalCost = parseFloat(totalCost);

    if(evaluator == "+") {
      newPrice = totalCost + price;
    }
    else if(evaluator == "-") {
      newPrice = totalCost - price;
    }

    document.querySelector("#totalCost").children[0].textContent = `$${newPrice.toFixed(2)}`;
  }

  function addNum(product_id, price) {
    num_field = document.querySelector(`input[name="order[products][${product_id}]"]`);
    val = num_field.value;
    if(val < 10) {
      num_field.value = parseInt(val, 10) + 1;
      updateCost(price, '+');
    }
  }

  function subNum(product_id, price) {
    num_field = document.querySelector(`input[name="order[products][${product_id}]"]`);
    val = num_field.value;
    if(val > 0) {
      num_field.value = parseInt(val, 10) - 1;
      updateCost(price, '-');
    }
  }
</script>

app/views/orders/edit.html.erb
<h1>Editando Orden</h1>

<%= render 'form', order: @order %>
<%= link_to 'Back', @order %>

app/views/orders/index.html.erb
<main class="container">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">Órdenes Activas</h6>
    <% @active_orders.each do |order| %>
      <%= link_to order, class: "order-link" do %>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

          <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
            <div class="d-flex justify-content-between">
              <strong class="text-gray-dark"><%= order.name %> ($<%= order.get_price %>)</strong>
              <%= link_to 'Cambiar Estado', update_status_path(order), method: :patch %>
            </div>
            <span class="d-block">Fecha de Entrega: <strong><%= order.delivery_date.strftime("%d/%m/%Y") %></strong>, Estado: <strong><%= order.get_status %></strong> </span>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">Órdenes Completadas (20 más recientes)</h6>
    <% @completed_orders.each do |order| %>
      <%= link_to order, class: "order-link" do %>
        <div class="d-flex text-muted pt-3">
          <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>

          <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
            <div class="d-flex justify-content-between">
              <strong class="text-gray-dark"><%= order.name %> ($<%= order.get_price %>)</strong>
            </div>
            <span class="d-block">Fecha de Entrega: <strong><%= order.delivery_date.strftime("%d/%m/%Y") %></strong>, Estado: <strong><%= order.get_status %></strong> </span>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

app/views/orders/new.html.erb
<h1>Nueva Orden</h1>
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<section class="mt-3">
  <!--Grid row-->
  <div class="row">
    <!--Grid column-->
    <div class="col-lg-8">
        <!-- Card -->
        <div class="card wish-list mb-3">
            <div class="card-body">
                <h5 class="mb-4">Productos</h5>
                <% @invoices.each do |i| %>
                    <div class="row mb-4">
                        <div class="col-md-5 col-lg-3 col-xl-3">
                            <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                <% if i.product.photo.attached? %>
                                    <%= image_tag i.product.photo, class: "img-fluid w-100"%>
                                <% else %>
                                    <img class="img-fluid w-100" src="https://expertphotography.com/wp-content/uploads/2019/03/Chocolate-Cake-Darina-Kopcok-Expert-Phtography.jpg" alt="Sample">
                                <% end %>
                            </div>
                        </div>
                        <div class="col-md-7 col-lg-9 col-xl-9">
                            <div>
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <h5><%= i.product.name %></h5>
                                        <h5>Cantidad: <%= i.quantity %></h5>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <p class="mb-0"><span><strong>$<%= i.product.price %></strong></span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="mb-4">
                <% end %>
            </div>
        </div>
        <!-- Card -->

      <!-- Card -->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4">

      <!-- Card -->
      <div class="card mb-3">
        <div class="card-body">

          <h5 class="mb-3">Información de Orden</h5>

          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Nombre
              <span><%= @order.name %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Estado
              <span><%= @order.get_status %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
              Fecha de Entrega
              <span><%= @order.delivery_date %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
              <div>
                <strong>Total</strong>
              </div>
              <span id="totalCost"><strong>$<%= @order.get_price %></strong></span>
            </li>
          </ul>

          <%= link_to 'Editar', edit_order_path(@order), class: "btn btn-primary btn-block waves-effect waves-light" %>
          <%= link_to 'Eliminar', @order, class: "btn btn-danger btn-block waves-effect waves-light", method: :delete, data: { confirm: 'Segura?' } %>

        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->
</section>
<!--Section: Block Content-->