config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders
  patch '/orders/:id/update_status', to: 'orders#update_status', as: 'update_status'
  root to: "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
    after_update_commit {broadcast_replace_to "products"}
    after_destroy_commit {broadcast_remove_to "products"}

    has_many :invoices
    has_many :orders, through: :invoices
    has_one_attached :photo, dependent: :destroy
    validates :name, :price, presence: true
    validates :price, numericality: {greater_than: 0}
    validates :photo, content_type: {in: %w[image/jpeg image/png image/jpg], message: "Formato equivocado de imagen"},
        size: {less_than: 5.megabytes, message: "El tamaño de la imagen no debe de exceder 5MB"}
    accepts_nested_attributes_for :invoices
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:edit, :update, :destroy, :show]
    before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]

    #GET /products
    def index
      @products = Product.all.order(:name)
    end

    #GET /products/new
    def new
      @product = Product.new
    end

    #GET /products/edit
    def edit
    end

    #POST /products
    def create
      @product = Product.new(product_params)
      respond_to do |format|
        if @product.save
          format.turbo_stream
          format.html { redirect_to products_url, notice: "#{@product.name} fue creado!" }
          format.json { render :show, status: :created, location: @product}
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    #PATCH/PUT /products/:id
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.turbo_stream { render turbo_stream: turbo_stream.append("toasts", partial: "shared/toast", locals: {title: "Editar Producto", message: "El producto fue actualizado!"})}
          format.html { redirect_to @product, notice: "#{@product.name} fue actualizado!" }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { redner json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    #DELETE /products/:id
    def destroy
      @product.destroy
      respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.append("toasts", partial: "shared/toast", locals: {title: "Eliminar Producto", message: "El producto fue eliminado!"})}
          format.html { redirect_to products_url, notice: 'Product was successfully deleted' }
          format.json { head :no_content }
      end
    end

    private

    def set_product
      @product = Product.find_by(id: params[:id])
    end

    def product_params 
      params.require(:product).permit(:name, :price, :photo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_alert.html.erb
<div class="alert alert-danger">
    Los siguientes errores evitaron que el producto se almacenara:
    <ul>
        <% product.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>
</div>

app/views/products/_edit_form.html.erb
<%= simple_form_for @product do |f| %>
    <div class="col">
        <div class="card shadow-sm">
            <div class="container-fluid">
                <% if product.photo.attached? %>
                    <%= image_tag(product.photo, width: "100%", height: "225") %> 
                <% else %>
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> 
                <% end %>
                <div class="photo-button"><%= f.input :photo, as: :file, wrapper: false, label: false %></div>
            </div>

            <div class="card-body">
                <%= f.input :name, label_html: {class: 'card-text'} %>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <% if action_name == "edit" %>
                          <%= f.submit "Editar", class: "btn btn-sm btn-outline-secondary" %>
                        <% else %>
                          <%= f.submit "Crear", class: "btn btn-sm btn-outline-secondary" %>
                        <% end %>
                        <%= link_to "Cancelar", @product, class: "btn btn-sm btn-outline-secondary" %>
                    </div>
                    <%= f.input :price, label_html: {class: "text-muted"} %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/products/_product.html.erb
<%= turbo_frame_tag dom_id(product) do %>
    <div class="col">
        <div class="card shadow-sm">
            <% if product.photo.attached? %>
                <%= image_tag(product.photo, width: "100%", height: "225") %> 
            <% else %>
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> 
            <% end %>

            <div class="card-body">
                <p class="card-text" id="name_<%= product.id %>"><%= product.name %></p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <%= link_to "Editar", edit_product_path(product) ,class: "btn btn-sm btn-outline-secondary" %>
                        <%= link_to "Eliminar", product, class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: "¿Seguro que quieres eliminar #{product.name}?"} %>
                    </div>
                    <small class="text-muted" id="price_<%= product.id %>">$<%= product.price %></small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/products/_product_card.html.erb
<div class="col">
    <div class="card shadow-sm">
        <% if product.photo.attached? %>
            <%= image_tag(product.photo, width: "100%", height: "225") %> 
        <% else %>
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> 
        <% end %>

        <div class="card-body">
            <p class="card-text" id="name_<%= product.id %>"><%= product.name %></p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <% if user_signed_in? %>
                        <%= link_to "Editar", edit_product_path(product) ,class: "btn btn-sm btn-outline-secondary", remote: true, "data-bs-toggle" => "modal", "data-bs-target" => "#exampleModal" %>
                        <%= link_to "Eliminar", product, class: "btn btn-sm btn-outline-danger", method: :delete %>
                    <% end %>
                </div>
                <small class="text-muted" id="price_<%= product.id %>">$<%= product.price %></small>
            </div>
        </div>
    </div>
</div>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.replace "new_product", partial: "products/product", locals: { product: @product } %>
<%= turbo_stream.append "products", partial: "shared/new_product_btn" %>
<%= turbo_stream.append "toasts", partial: "shared/toast", locals: { title: "Nuevo Producto", message: "#{@product.name} fue creado" } %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= turbo_frame_tag dom_id(@product) do %>
    <%= render 'edit_form', product: @product %>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Productos</h1>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <% if user_signed_in? %>
        <%= turbo_stream_from "products" %>
        <%= turbo_frame_tag "products", class: "row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" do %>
          <%= render @products, user: current_user %>
          <%= render 'shared/new_product_btn' if user_signed_in? %>
        <% end %>
      <% else %>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" >
          <% @products.each do |p| %>
            <%= render 'product_card', product: p %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</main>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= turbo_frame_tag dom_id(@product) do %>
    <%= render 'edit_form', product: @product %>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@product) do %>
  <%= render @product %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) if user_signed_in? %> |
<%= link_to 'Back', products_path %>